package com.example.smartfit.domain.model

/**
 * DOMAIN MODEL - Activity
 *
 * This represents a fitness activity in the app's business logic layer.
 * It's the "UI-friendly" version of the data.
 *
 * DOMAIN LAYER PURPOSE:
 * The domain layer contains models that represent business concepts without
 * any framework-specific dependencies. They're pure Kotlin data classes.
 *
 * WHY SEPARATE FROM DATABASE ENTITY?
 * ✓ UI doesn't need to know about database (@Entity, @PrimaryKey, etc.)
 * ✓ Can combine data from multiple sources (DB + API)
 * ✓ Can have computed properties or business logic
 * ✓ Easier to test (no Android dependencies)
 * ✓ Follows Clean Architecture principles
 *
 * CONVERSION FLOW:
 * Database Entity → Domain Model → UI
 * ActivityEntity.toDomain() → Activity → Display in Composable
 *
 * This model represents a single fitness activity entry (workout, run, walk, etc.)
 */
data class Activity(
    /**
     * Unique identifier for the activity
     * Generated by Room database when inserted
     */
    val id: Int = 0,

    /**
     * Type of activity
     * Examples: "Running", "Cycling", "Swimming", "Weight Training", "Walking", "Yoga"
     */
    val type: String,

    /**
     * Duration in minutes
     * How long the activity lasted
     */
    val durationMinutes: Int,

    /**
     * Estimated calories burned during this activity
     * Calculated based on duration, activity type, and user metrics
     */
    val caloriesBurned: Int,

    /**
     * Distance covered (for activities like running, cycling)
     * In kilometers. Null for activities where distance doesn't apply (weight training)
     */
    val distanceKm: Double? = null,

    /**
     * Number of steps (for walking/running)
     * Null for activities where steps don't apply
     */
    val steps: Int? = null,

    /**
     * Timestamp when activity was completed
     * Stored as Unix timestamp (milliseconds since Jan 1, 1970)
     * Use Date(timestamp) or Instant.ofEpochMilli(timestamp) to convert to date
     */
    val timestamp: Long,

    /**
     * Optional notes about the activity
     * Example: "Morning run, felt great!", "New PR on bench press!"
     */
    val notes: String? = null
) {
    /**
     * COMPUTED PROPERTY - Calories per minute
     *
     * This is a business logic property that doesn't need to be stored in the database
     * It's calculated on-the-fly when needed
     *
     * Used for: Comparing activity intensity, showing stats
     */
    val caloriesPerMinute: Double
        get() = if (durationMinutes > 0) {
            caloriesBurned.toDouble() / durationMinutes
        } else {
            0.0
        }

    /**
     * COMPUTED PROPERTY - Activity intensity level
     *
     * Categorizes activity based on calories burned per minute
     * Useful for showing badges, colors, or icons in UI
     */
    val intensityLevel: IntensityLevel
        get() = when {
            caloriesPerMinute >= 10.0 -> IntensityLevel.HIGH
            caloriesPerMinute >= 6.0 -> IntensityLevel.MEDIUM
            else -> IntensityLevel.LOW
        }
}

/**
 * Intensity level enum
 * Represents how intense a workout was
 */
enum class IntensityLevel {
    LOW,      // Light activity (walking, yoga)
    MEDIUM,   // Moderate activity (jogging, cycling)
    HIGH      // Intense activity (running, HIIT, sports)
}

/**
 * EXAMPLE USAGE IN UI:
 *
 * ```kotlin
 * @Composable
 * fun ActivityCard(activity: Activity) {
 *     Card {
 *         Column {
 *             Text(activity.type)
 *             Text("${activity.durationMinutes} min")
 *             Text("${activity.caloriesBurned} cal")
 *
 *             // Use computed property
 *             Text(
 *                 text = "Intensity: ${activity.intensityLevel}",
 *                 color = when(activity.intensityLevel) {
 *                     IntensityLevel.LOW -> Color.Green
 *                     IntensityLevel.MEDIUM -> Color.Yellow
 *                     IntensityLevel.HIGH -> Color.Red
 *                 }
 *             )
 *
 *             // Show distance only if present
 *             activity.distanceKm?.let {
 *                 Text("Distance: $it km")
 *             }
 *         }
 *     }
 * }
 * ```
 *
 * MOCK DATA FOR TESTING:
 * ```kotlin
 * val sampleActivity = Activity(
 *     id = 1,
 *     type = "Running",
 *     durationMinutes = 30,
 *     caloriesBurned = 300,
 *     distanceKm = 5.0,
 *     steps = 6500,
 *     timestamp = System.currentTimeMillis(),
 *     notes = "Morning run in the park"
 * )
 * ```
 */
